public array $allProperties = [
        'age' => [
            'type'    => 'number',
            'actions' => ['>' => 'More Than', '=' => 'Equal', '<' => 'Less Than'],
            'options' => [],
            'table'   => '',
            'column'  => 'date_of_birth',
        ],
        'app_version' => [
            'type'    => 'select2',
            'actions' => ['IN' => 'Exist', 'NOT IN' => 'Not Exist'],
            'options' => [],
            'table'   => 'deviceTokens',
            'column'  => 'app_version',
        ],
        'date_of_birth' => [
            'type'    => 'date',
            'actions' => ['=' => 'Equal', '>' => 'More Than', '<' => 'Less Than'],
            'options' => [],
            'table'   => '',
            'column'  => 'date_of_birth',
        ],
        'device_type' => [
            'type'    => 'select2',
            'actions' => ['IN' => 'Exist', 'NOT IN' => 'Not Exist'],
            'options' => [],
            'table'   => 'deviceAuthorizations',
            'column'  => 'type',
        ],
        'email_provider' => [
            'type'    => 'text',
            'actions' => ['LIKE' => 'Contains', 'NOT LIKE' => 'Doesn\'t Contains'],
            'options' => [],
            'table'   => '',
            'column'  => 'email',
        ],
        'gender' => [
            'type'    => 'select',
            'actions' => ['=' => 'Equal'],
            'options' => [],
            'table'   => '',
            'column'  => 'gender',
        ],
        'last_active_date' => [
            'type'    => 'date',
            'actions' => ['=' => 'Equal', '>' => 'More Than', '<' => 'Less Than'],
            'options' => [],
            'table'   => 'deviceAuthorizations',
            'column'  => 'last_used_at',
        ],
        'last_logged_in' => [
            'type'    => 'date',
            'actions' => ['=' => 'Equal', '>' => 'More Than', '<' => 'Less Than'],
            'options' => [],
            'table'   => '',
            'column'  => 'last_login_at',
        ],
        'payment_method' => [
            'type'    => 'select2',
            'actions' => ['IN' => 'Exist', 'NOT IN' => 'Not Exist'],
            'options' => [],
            'table'   => 'payments',
            'column'  => 'method',
        ],
        'MSISDN' => [
            'type'    => 'text',
            'actions' => ['start_with' => 'Start With', 'LIKE' => 'Contains'],
            'options' => [],
            'table'   => '',
            'column'  => 'phone',
        ],
        'platform' => [
            'type'    => 'select2',
            'actions' => ['IN' => 'Exist', 'NOT IN' => 'Not Exist'],
            'options' => [],
            'table'   => 'deviceTokens',
            'column'  => 'platform',
        ],
        'signup_date' => [
            'type'    => 'date',
            'actions' => ['=' => 'Equal', '>' => 'More Than', '<' => 'Less Than'],
            'options' => [],
            'table'   => '',
            'column'  => 'created_at',
        ],
        'subscribed_package' => [
            'type'    => 'select',
            'actions' => ['=' => 'Equal'],
            'options' => [],
            'table'   => 'purchases',
            'column'  => 'purchasable_id',
        ],
        'subscription_expiring_in_(x_days)' => [
            'type'    => 'number',
            'actions' => ['=' => 'Equal', '>' => 'More Than', '<' => 'Less Than'],
            'options' => [],
            'table'   => 'purchases',
            'column'  => 'expires_at',
        ],
        'subscription_expiration' => [
            'type'    => 'date',
            'actions' => ['=' => 'Equal', '>' => 'More Than', '<' => 'Less Than'],
            'options' => [],
            'table'   => 'purchases',
            'column'  => 'expires_at',
        ],
        'subscription_status' => [
            'type'    => 'select2',
            'actions' => ['IN' => 'Exist', 'NOT IN' => 'Not Exist', 'not_exist' => 'Not Subscribed'],
            'options' => [],
            'table'   => 'purchases',
            'column'  => 'status',
        ],